language: r
sudo: false
cache: packages
branches:
    only:
        - master
        - stable
        - develop
matrix:
    include:
    - os: linux
      r: devel
      r_check_args: --as-cran --run-dontrun --run-donttest
    - os: linux
      r: release
      r_check_args: --as-cran --run-dontrun --run-donttest
    - os: linux
      r: oldrel
      r_check_args: --as-cran --run-dontrun --run-donttest
    - os: osx
      r: release
      r_build_args: --no-build-vignettes --no-manual
      r_check_args: --no-build-vignettes --no-vignettes --no-codoc --no-manual --as-cran --run-dontrun --run-donttest
      warnings_are_errors: false
r_github_packages:
  - jimhester/covr
  - kaneplusplus/bigmemory
after_success:
  - Rscript -e 'covr::codecov()'
